kind: ConfigMap
apiVersion: v1
metadata:
  name: dynamic-plugins-rhdh
  labels:
    rhdh.redhat.com/ext-config-sync: "true"
  annotations:
    rhdh.redhat.com/backstage-name: "developer-hub"
data:
  dynamic-plugins.yaml: |
    includes:
      - dynamic-plugins.default.yaml
    plugins:
      - package: 'http://plugin-registry:8080/internal-backstage-plugin-mta-backend-dynamic-0.1.0.tgz'
        disabled: false
        integrity: 'sha512-nkxVPQ2JAM+eE/8HRLwuAzstkvBXwk9c5tpmkrPksfefojYCtEbFPjFCf59WFBXeHmuD6/hQPJRus97Uf7TT1g=='
      - package: 'http://plugin-registry:8080/internal-backstage-plugin-mta-frontend-dynamic-0.1.0.tgz'
        disabled: false
        integrity: 'sha512-xYlMnvf5AVs522uQOsfTyZVx3p89Ko/h+M2pgL02pMlihYFbTSXpi6jSvNjae5qJ3WFJn0UWoXRUDLhmzyWh9A'
      - package: 'http://plugin-registry:8080/internal-backstage-plugin-catalog-backend-module-mta-entity-provider-dynamic-0.1.0.tgz'
        disabled: false
        integrity: 'sha512-m6bf0cy9xWfOdtRnCQqWXBgbEGgPFKatyhxhXI6yhJpaRk2pY08l1ECbw5qGX6h2clztS49URQoNgKuWtu1PFQ=='
      - package: 'http://plugin-registry:8080/internal-backstage-plugin-scaffolder-backend-module-mta-dynamic-0.1.0.tgz'
        disabled: false
        integrity: 'sha512-EeEhDNDOCwlJ60tGgv6R9OmtbMkn3FpVznI/ogRSfwz5pROzixaAIzGIJHwzWgGCPY7wOAk3l4EXT+Bf+Qbj6A=='
